"""Add role and is_active fields to users table

Revision ID: deca8d9699b3
Revises: 001
Create Date: 2025-09-13 14:58:06.333473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deca8d9699b3'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing data
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    
    # Update existing admin user (if exists) to have admin role
    op.execute("UPDATE users SET role = 'admin' WHERE username = 'admin'")
    
    # Remove server defaults after populating existing data
    op.alter_column('users', 'role', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)
    
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
