"""Add audit_log table for security and audit system

Revision ID: 23c847e56cfe
Revises: deca8d9699b3
Create Date: 2025-09-13 16:30:43.180195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c847e56cfe'
down_revision = 'deca8d9699b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
